version: '2'
services:
  nginx:
   container_name: www
   image: nginx
   restart: always
   ports:
   - 4443:443
   - 80:80
   volumes:
   - ./config/nginx.conf:/etc/nginx/nginx.conf
   - ./config/sites:/tmp/nginx-config-templates
   - ./entrypoint.sh:/entrypoint.sh
   - ./static/nats/html:/var/www/nats/html
   - ./static/sportsbook/html:/var/www/sportsbook/html
   environment:
   - NGINX_PORT=80
   - NATS_SERVER_NAME=nats.intralot.com
   - NATS_DOCUMENT_ROOT=/var/www/nats/html
   - SB_SERVER_NAME=sportsbook.intralot.com
   - SB_DOCUMENT_ROOT=/var/www/sportsbook/html
   command: ./entrypoint.sh
   networks:
     - front

  hornetq:
    container_name: hornetq
    image: mansante/hornetq
    restart: always
    ports:
      - 5445:5445
      - 5455:5455
    environment:
      - HORNETQ_VERSION=2.4.0.Final
      - HORNETQ_HOME="/opt/hornetq-${HORNETQ_VERSION}"
    volumes:
      - mqdata
      - ./hornetq/config/hornetq-jms.xml:/opt/hornetq-2.4.0.Final/config/stand-alone/non-clustered/hornetq-jms.xml
    networks:
      - back


  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - dbdata
      - ./postgres/init.d:/docker-entrypoint-initdb.d/
    networks:
      - back


  jetty:
   container_name: app
   image: jetty
   restart: always
   ports:
     - 8081:8080
   volumes:
     - /tmp/sample.war:/var/lib/jetty/webapps/sample.war
   networks:
     - front
     - back


networks:
  front:
  back:
volumes:
  dbdata:
  mqdata:
